# Introduction
There has been recent discourse over the increased use of generative AI amongst students. Due to this rising trend I think it's important to understand its possible implications as it pertains to scholastic performance, and its use. To help me gain some insight into this increase in popularity of generative AI I'll be analyzing a dataset collected from students at the collegiate level.  
## Goal
My goal for this project is to identify driving factors for the adoption of generative AI amongst students and its effect on academic performance.
### Questions
1. What is the most common use for generative AI?
2. Is there a relationship between academic performance and generative AI use?
3. Is there a stronger correlation between academic performance and generative AI use than academic performance and traditional studying?

In [9]:
#import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
#load data
data = pd.read_csv('ai_student_impact_dataset_original.csv')

data.head(10)

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
5,100006,STEM,Junior,3.449,6.50,Debugging/Troubleshooting,Beginner,1,False,14.19,4,Allowed_With_Citation,5,3.666,65.92,High
6,100007,STEM,Freshman,3.622,31.41,Summarizing_Reading,Advanced,5,True,13.11,8,Allowed_With_Citation,7,4.000,67.97,Medium
7,100008,Arts,Junior,2.746,5.33,Copywriting/Drafting,Intermediate,3,False,18.45,2,Actively_Encouraged,1,2.965,85.09,Medium
8,100009,Business,Sophomore,3.420,2.00,Debugging/Troubleshooting,Beginner,2,True,2.87,1,Strict_Ban,5,3.396,55.71,Medium
9,100010,Business,Sophomore,3.046,19.99,Debugging/Troubleshooting,Intermediate,2,True,12.49,3,Strict_Ban,8,2.978,87.18,High

In [11]:
#data information
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  50000 non-null  int64
 1   Major_Category              50000 non-null  str
 2   Year_of_Study               50000 non-null  str
 3   Pre_Semester_GPA            50000 non-null  float64
 4   Weekly_GenAI_Hours          50000 non-null  float64
 5   Primary_Use_Case            50000 non-null  str
 6   Prompt_Engineering_Skill    50000 non-null  str
 7   Tool_Diversity              50000 non-null  int64
 8   Paid_Subscription           50000 non-null  bool
 9   Traditional_Study_Hours     50000 non-null  float64
 10  Perceived_AI_Dependency     50000 non-null  int64
 11  Institutional_Policy        50000 non-null  str
 12  Anxiety_Level_During_Exams  50000 non-null  int64
 13  Post_Semester_GPA           50000 non-null  float64
 14  Skill_Retention_Score       50000 non-null  float64
 15  Burnout_Risk_Level          50000 non-null  str
dtypes: bool(1), float64(5), int64(4), str(6)
memory usage: 5.8 MB

In [12]:
#data description
data.describe(include = 'all')

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
count,50000.000000,50000,50000,50000.000000,50000.000000,50000,50000,50000.00000,50000,50000.000000,50000.000000,50000,50000.000000,50000.000000,50000.000000,50000
unique,NaN,5,5,NaN,NaN,5,3,NaN,2,NaN,NaN,3,NaN,NaN,NaN,3
top,NaN,STEM,Junior,NaN,NaN,Debugging/Troubleshooting,Beginner,NaN,False,NaN,NaN,Allowed_With_Citation,NaN,NaN,NaN,Medium
freq,NaN,15059,11045,NaN,NaN,12295,18495,NaN,28846,NaN,NaN,25224,NaN,NaN,NaN,21144
mean,125000.500000,NaN,NaN,3.146102,8.427752,NaN,NaN,2.80026,NaN,11.209271,3.505360,NaN,4.270760,3.349299,75.798125,NaN
std,14433.901067,NaN,NaN,0.478854,8.269490,NaN,NaN,1.18802,NaN,5.156426,1.820812,NaN,2.144066,0.495673,13.281626,NaN
min,100001.000000,NaN,NaN,1.183000,0.000000,NaN,NaN,1.00000,NaN,1.000000,1.000000,NaN,1.000000,1.000000,10.780000,NaN
25%,112500.750000,NaN,NaN,2.834000,2.390000,NaN,NaN,2.00000,NaN,7.560000,2.000000,NaN,3.000000,3.023750,66.820000,NaN
50%,125000.500000,NaN,NaN,3.210000,5.800000,NaN,NaN,3.00000,NaN,11.180000,3.000000,NaN,4.000000,3.421000,76.000000,NaN
75%,137500.250000,NaN,NaN,3.521000,11.720000,NaN,NaN,4.00000,NaN,14.710000,5.000000,NaN,6.000000,3.749000,85.190000,NaN
max,150000.000000,NaN,NaN,3.998000,40.000000,NaN,NaN,5.00000,NaN,35.860000,10.000000,NaN,10.000000,4.000000,100.000000,NaN

In [13]:
#view columns
data.columns

Index(['Student_ID', 'Major_Category', 'Year_of_Study', 'Pre_Semester_GPA',
       'Weekly_GenAI_Hours', 'Primary_Use_Case', 'Prompt_Engineering_Skill',
       'Tool_Diversity', 'Paid_Subscription', 'Traditional_Study_Hours',
       'Perceived_AI_Dependency', 'Institutional_Policy',
       'Anxiety_Level_During_Exams', 'Post_Semester_GPA',
       'Skill_Retention_Score', 'Burnout_Risk_Level'],
      dtype='str')

In [14]:
#check for exact duplicates
exact_dups = data.duplicated().sum()
print(f"Number of exact duplicate rows: {exact_dups}")

#check for parital duplicates based on Student ID 
partial_dups = data.duplicated(subset = ['Student_ID']).sum()
print(f"Number of partial duplicate rows based on Student ID: {partial_dups}")

Number of exact duplicate rows: 0
Number of partial duplicate rows based on Student ID: 0